var express = require('express');
var app = express();
var cors = require('cors')

//app.get('/', (req, res) => res.send('hello world'))
app.use(cors())
app.get('/edit', (req, res) => res.send('Youre now on the editing page'))
app.listen(3000, () => console.log('App listening on port 3000'))

// setting up mongodb connection (using mongoose)
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var cardSchema = new Schema({
    title: String, 
    content: String
});

//-----------CODE TO ADD CARDS TO MONGO
 var Card = mongoose.model('Card', cardSchema);
// var card1 = new Card ({title: "Card from mongo", content: 'This is a card generated by content from mongo and mongoose schema'})
// card1.save(function (err, card1){
//     if (err) return console.err(err);
//     console.log('Card Saved')
// })

//-----------CODE TO OUTPUT CARDS TO SCREEN
Card.find(function(err, cards){
    if(err) return console.error(err);
    app.get('/', (req, res) => res.send(cards))
})

mongoose.connect('mongodb://localhost/mello');

var db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error: '));
db.once('open', function (){
    //we;re connected in here
    console.log('Its now connected')
})

